apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output 
  template:
    metadata:
      labels:
        app: log-output 
    spec:
      volumes:
        - name: log-volume
          emptyDir: {}
        - name: config-volume
          configMap:
            name: log-output-config
            items:
              - key: information.txt
                path: information.txt
      containers:
        - name: writer 
          image: nlinnanen/log_output_writer:v2
          env:
            - name: OUTPUT_PATH
              value: "/logs/output.txt"
          volumeMounts:
            - name: log-volume
              mountPath: "/logs"
        - name: server
          image: nlinnanen/log_output_server:v8
          env:
            - name: LOG_PATH
              value: "/logs/output.txt"
            - name: PORT
              value: "8080"
            - name: COUNT_URL
              value: "http://pong-svc:2345/pingpong/count"
            - name: FILE_PATH
              value: "/config/information.txt"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: message
          volumeMounts:
            - name: log-volume
              mountPath: "/logs"
            - name: config-volume
              mountPath: "/config"
