apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: pong 
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 8080