apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output 
  template:
    metadata:
      labels:
        app: log-output 
    spec:
      volumes:
        - name: log-volume
          emptyDir: {}
        - name: shared-logpong
          persistentVolumeClaim:
            claimName: logpong-claim
      containers:
        - name: writer 
          image: nlinnanen/log_output_writer:v2
          env:
            - name: OUTPUT_PATH
              value: "/logs/output.txt"
          volumeMounts:
            - name: log-volume
              mountPath: "/logs"
        - name: server
          image: nlinnanen/log_output_server:v2
          env:
            - name: LOG_PATH
              value: "/logs/output.txt"
            - name: PORT
              value: "8080"
            - name: COUNT_PATH
              value: "/count/output.txt"
          volumeMounts:
            - name: shared-logpong
              mountPath: "/count"
            - name: log-volume
              mountPath: "/logs"
