apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong 
  template:
    metadata:
      labels:
        app: pong 
    spec:
      volumes:
        - name: shared-logpong
          persistentVolumeClaim:
            claimName: logpong-claim
      containers:
        - name: pong 
          image: nlinnanen/pong:v2
          env:
            - name: COUNT_FILE
              value: "/logs/output.txt"
          volumeMounts:
            - name: shared-logpong
              mountPath: "/logs"