apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app 
  template:
    metadata:
      labels:
        app: todo-app 
    spec:
      volumes:
        - name: shared-todo
          persistentVolumeClaim:
            claimName: todo-claim
      containers:
        - name: todo-app 
          image: nlinnanen/todo_app:v4
          env:
            - name: IMAGE_URL
              value: "https://picsum.photos/1200"
            - name: IMAGE_PATH
              value: "/app/static/image.jpg"
            - name: TODO_URL
              value: "http://todo-backend-svc:2345/todos"
          volumeMounts:
            - name: shared-todo
              mountPath: "/app/static"