apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-claim
  namespace: project 
spec:
  storageClassName: todo-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi